version: "3"

services:
  nginx:
    image: nginx:alpine
    ports:
      - 8000:80
    volumes:
      - ./app:/var/www
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
  app:
    build: ./docker/app
    volumes:
      - ./app:/var/www
  db:
    image: mysql:8
    command:
      - "--default-authentication-plugin=mysql_native_password"
    environment:
      - MYSQL_USER=db_user
      - MYSQL_DATABASE=db_name
      - MYSQL_PASSWORD=db_password
      - MYSQL_ROOT_PASSWORD=db_password
networks:
  default:
